# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: ^.*\b(migrations)\b.*$
        args: [ "--profile", "black" ]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args:
          [
            --max-line-length=88,
            --ignore,
            "E203,E501,W503,W504",
            "--exclude",
            "*test*",
          ]

  - repo: https://github.com/pycqa/autoflake
    rev: "v2.2.1"
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--exclude",
            "*test*",
          ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        types: [ python ]
        exclude: ^.*example.*$
        additional_dependencies: [ pandas-stubs, types-requests, types-PyYAML, pydantic ]
